In [1]:
print("Hello")

Hello

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/jobs.csv")

In [4]:
print("Before Cleaning:")
print(df.shape)

Before Cleaning:
(607, 12)

In [5]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [6]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [7]:
df.duplicated().sum()

42

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

In [10]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [11]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [12]:
experience_map = {
    "EN":"Entry Level",
    "MI":"Mid Level",
    "SE":"Senior Level",
    "EX":"Executive Level"
}

df["experience_level_name"] = df["experience_level"].map(experience_map)

In [13]:
df[["experience_level","experience_level_name"]].head()

  experience_level experience_level_name
0               MI             Mid Level
1               SE          Senior Level
2               SE          Senior Level
3               MI             Mid Level
4               SE          Senior Level

In [14]:
employment_map = {
    "FT":"Full Time",
    "PT":"Part Time",
    "CT":"Contract",
    "FL":"Freelance"
}

df["employment_type_name"] = df["employment_type"].map(employment_map)

In [15]:
df[["employment_type","employment_type_name"]].head()

  employment_type employment_type_name
0              FT            Full Time
1              FT            Full Time
2              FT            Full Time
3              FT            Full Time
4              FT            Full Time

In [16]:
df["salary_category"] = pd.cut(
    df["salary_in_usd"],
    bins=[0,50000,100000,150000,500000],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [17]:
df["salary_category"].value_counts()

salary_category
Medium       183
High         142
Very High    132
Low          107
Name: count, dtype: int64

In [18]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_name,employment_type_name,salary_category
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,Mid Level,Full Time,Medium
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Senior Level,Full Time,Very High
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,Senior Level,Full Time,High
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Mid Level,Full Time,Low
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,Senior Level,Full Time,High

In [19]:
df.to_csv(
    "../data/processed/cleaned_jobs.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [20]:
cleaned_df = pd.read_csv(
    "../data/processed/cleaned_jobs.csv"
)

cleaned_df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_name,employment_type_name,salary_category
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,Mid Level,Full Time,Medium
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Senior Level,Full Time,Very High
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,Senior Level,Full Time,High
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Mid Level,Full Time,Low
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,Senior Level,Full Time,High

In [21]:
cleaned_df.shape

(565, 14)

In [22]:
cleaned_df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size',
       'experience_level_name', 'employment_type_name', 'salary_category'],
      dtype='object')